import "./globals.css";
import { Inter, Manrope, Poppins } from "next/font/google";
import { cx } from "../utils.js";
import Header from "../components/header";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-in",
});

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mr",
});

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-pop",
  weight: "400"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
      className={cx(inter.variable, manrope.variable, poppins.variable, "font-poppins bg-light")}>
        <Header />
        {children}
      </body>
    </html>
  );
}
